name = "Lark"
uuid = "d38f95b0-bddf-11e9-2f4c-594bc4765394"
authors = ["Erez Shinan <erezshin@gmail.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
